# This file was generated by GoReleaser. DO NOT EDIT.
cask "teleskopio" do
  name "teleskopio"
  desc "teleskopio is an open-source small and beautiful Web Kubernetes client."
  homepage "https://github.com/roman-kiselenko/teleskopio"
  version "0.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teleskopio"

  on_macos do
    on_intel do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_darwin_amd64.tar.gz"
      sha256 "145e651dc300161aff5634176c060cba7cd989369d0b24513fdccc2b16e7257e"
    end
    on_arm do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_darwin_arm64.tar.gz"
      sha256 "92cfbc8d90a11b28f308f206b5adb33e05cbbb14e4c4da61b32051339cd154dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_linux_amd64.tar.gz"
      sha256 "469ddfd00f8a0da3b86f5d0ac5f020377a9967fb7117725f9d5091eca3a8d40c"
    end
    on_arm do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_linux_arm64.tar.gz"
      sha256 "b54c37d583d54af1d8953738b03a0ec26b2d6a622432047c746ddf425c66a061"
    end
  end

  caveats do
    "teleskopio --config=config.yaml"
  end

  # No zap stanza required
end
