# This file was generated by GoReleaser. DO NOT EDIT.
cask "teleskopio" do
  name "teleskopio"
  desc "teleskopio is an open-source small and beautiful Web Kubernetes client."
  homepage "https://github.com/roman-kiselenko/teleskopio"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teleskopio"

  on_macos do
    on_intel do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_darwin_amd64.tar.gz"
      sha256 "f55d0e595e050ebb326c4d456d14d4fe7f08b695a75f540443f321cd9de67a40"
    end
    on_arm do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_darwin_arm64.tar.gz"
      sha256 "4b8a30898e2c6ecd60f822c79a999d5b9702b643b9e700e2ceffc178411a5192"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_linux_amd64.tar.gz"
      sha256 "b123596bb8ad166f8e2209b98be527ee7dcab1fa83f13ea9be3a386971eb9227"
    end
    on_arm do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_linux_arm64.tar.gz"
      sha256 "2403d2e537cf78dedd4a80731b0ff36a4cbc42d3cc6fe8e425210e9760fa648f"
    end
  end

  caveats do
    "teleskopio --config=config.yaml"
  end

  # No zap stanza required
end
