# This file was generated by GoReleaser. DO NOT EDIT.
cask "teleskopio" do
  name "teleskopio"
  desc "teleskopio is an open-source small and beautiful Web Kubernetes client."
  homepage "https://github.com/roman-kiselenko/teleskopio"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teleskopio"

  on_macos do
    on_intel do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_darwin_amd64.tar.gz"
      sha256 "15502e3c7263d2c220fc86c030101cb4bb324d0ff59f5254bc4ed1bbfcd4d11c"
    end
    on_arm do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_darwin_arm64.tar.gz"
      sha256 "56e64951293bcfa9cb425544a9e34afa9fb442fd7f964d9262974cdff9d9a857"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_linux_amd64.tar.gz"
      sha256 "abadfea628b7aecc14842d280e273be94ff329aec9419f650b99600bfa0955e0"
    end
    on_arm do
      url "https://github.com/roman-kiselenko/teleskopio/releases/download/v#{version}/teleskopio_#{version}_linux_arm64.tar.gz"
      sha256 "19e6c29d8091ae553bf2b2f63f876ad99b4e048330f3d7a4e7ece97336c02e3c"
    end
  end

  caveats do
    "teleskopio --config=config.yaml"
  end

  # No zap stanza required
end
